log4j.rootLogger=INFO, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{HH:mm:ss,SSS} %-5p %-60c %x - %m%n
log4j.logger.com.ververica.cdc=ERROR
log4j.logger.io.debezium=ERROR
log4j.logger.org.apache.flink.runtime.checkpoint=ERROR
log4j.logger.org.apache.flink.runtime.source.coordinator=ERROR
log4j.logger.org.apache.flink.connector.kafka=ERROR
log4j.logger.org.apache.flink.runtime.taskexecutor=INFO
log4j.logger.org.apache.flink.runtime.jobmanager=INFO
log4j.logger.org.apache.hadoop.hdfs.protocol.datatransfer.sasl=ERROR
log4j.logger.org.apache.hadoop.hdfs=ERROR

log4j.logger.org.apache.kafka.clients=ERROR
log4j.logger.org.apache.kafka.clients.producer=ERROR
log4j.logger.org.apache.kafka.clients.consumer=ERROR
